[package]
name = "checksum"
version = "0.1.0"
edition = "2021"

[lints.clippy]
missing_safety_doc = "deny"
undocumented_unsafe_blocks = "deny"

[features]
default = ["ring"]
ring = ["argmin-crypto/ring"]
openssl = ["argmin-crypto/openssl"]
bench-select = []

[dependencies]
argmin-crypto = { path = "../crypto", default-features = false }
twox-hash = { version = "2.1.2", default-features = false, features = [
    "std",
    "xxhash64",
    "xxhash3_64",
    "xxhash3_128",
] }

[dev-dependencies]
proptest = "1"
