[workspace]
resolver = "2"
members = [
    "crates/observability",
    "crates/ec",
    "crates/checksum",
    "crates/s3-types",
    "crates/placement",
    "crates/storage",
    "crates/auth",
    "crates/server-core",
    "crates/server-http",
    "crates/argmin-s3",
    "crates/test-util",
    "crates/s3-tests",
    "crates/s3-http-tests",
    "crates/s3-local-tests",
]
