[package]
name = "s3-diff-tests"
version = "0.1.0"
edition = "2021"
publish = false
autotests = false

[features]
deep-tracing = ["s3-tests/deep-tracing"]

[dependencies]
s3-tests = { path = "../s3-tests" }
s3-types = { path = "../s3-types" }

[dev-dependencies]
auth = { path = "../auth" }
base64 = "0.22"
checksum = { path = "../checksum", default-features = false }
ring = "0.17"
serde_json = "1"
