[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[features]
deep-tracing = ["observability/deep-tracing"]
test-hooks = []

[dependencies]
checksum = { path = "../checksum", default-features = false }
ec = { path = "../ec", default-features = false }
observability = { path = "../observability" }
s3-types = { path = "../s3-types" }
rapidhash = "4.4"
rusqlite = { version = "0.33", features = ["bundled"] }
thiserror = "2"

[dev-dependencies]
test-util = { path = "../test-util" }
proptest = "1"
