[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[features]
deep-tracing = ["observability/deep-tracing"]
test-hooks = []

[dependencies]
checksum = { path = "../checksum", default-features = false }
ec = { path = "../ec", default-features = false }
futures-util = "0.3"
observability = { path = "../observability" }
openraft = { version = "=0.10.0-alpha.26", default-features = false, features = ["tokio-rt"] }
placement = { path = "../placement" }
s3-types = { path = "../s3-types" }
rapidhash = "4.4"
ring = "0.17"
rusqlite = { version = "0.33", features = ["bundled", "functions", "trace"] }
thiserror = "2"
tokio = { version = "1", features = ["rt"] }

[dev-dependencies]
test-util = { path = "../test-util" }
proptest = "1"
