[package]
name = "server-core"
version = "0.1.0"
edition = "2021"

[dependencies]
auth = { path = "../auth" }
checksum = { path = "../checksum", default-features = false }
ec = { path = "../ec", default-features = false }
observability = { path = "../observability" }
storage = { path = "../storage", default-features = false }
s3-types = { path = "../s3-types" }
base64 = "0.22"
rapidhash = "4.4"
ring = "0.17"
subtle = "2"
thiserror = "2"

[features]
test-utils = []
deep-tracing = [
    "auth/deep-tracing",
    "ec/deep-tracing",
    "observability/deep-tracing",
    "storage/deep-tracing",
]

[dev-dependencies]
proptest = "1"
storage = { path = "../storage", default-features = false, features = ["test-hooks"] }
test-util = { path = "../test-util" }
