[package]
name = "server-core"
version = "0.1.0"
edition = "2021"

[dependencies]
auth = { path = "../auth" }
checksum = { path = "../checksum", default-features = false }
ec = { path = "../ec", default-features = false }
observability = { path = "../observability" }
storage = { path = "../storage", default-features = false }
s3-types = { path = "../s3-types" }
base64 = "0.22"
rapidhash = "1"
ring = "0.17"
subtle = "2"
thiserror = "2"

[features]
test-utils = []

[dev-dependencies]
proptest = "1"
test-util = { path = "../test-util" }
