// Copyright The Argmin Authors.
// SPDX-License-Identifier: Apache-2.0

const STORAGE_RPC_FRAME_MAGIC: &[u8] = b"argmin-storage-rpc-frame";
pub(crate) const STORAGE_RPC_FRAME_ENCODING_VERSION: u16 = 31;
pub(crate) const STORAGE_RPC_MAX_PAYLOAD_LEN: usize = 64 * 1024 * 1024;
const STORAGE_RPC_FRAME_FIXED_LEN: usize =
    4 + STORAGE_RPC_FRAME_MAGIC.len() + 2 + 8 + 2 + 4 + 8;
pub(crate) const STORAGE_RPC_MAX_FRAME_LEN: usize =
    STORAGE_RPC_FRAME_FIXED_LEN + STORAGE_RPC_MAX_PAYLOAD_LEN;
const STORAGE_RPC_MAX_STAGING_ARTIFACT_BYTES: usize =
    METADATA_TRANSFER_STAGED_ARTIFACT_MAX_BYTES as usize;
const STORAGE_RPC_MAX_STAGING_AUTHORIZATION_BYTES: usize =
    MAX_UNAVAILABLE_PG_TRANSITION_COMMAND_BYTES;
const STORAGE_RPC_STAGING_AUTHORIZATION_PRESENTATION_OVERHEAD: usize = 8 + 32 + 4;
pub(crate) const STORAGE_RPC_STAGING_ARTIFACT_PUBLICATION_MAX_FRAME_LEN: usize = 4
    + STORAGE_RPC_FRAME_MAGIC.len()
    + 2
    + 8
    + 2
    + 4
    + 8
    + STORAGE_RPC_STAGING_AUTHORIZATION_PRESENTATION_OVERHEAD
    + STORAGE_RPC_MAX_STAGING_AUTHORIZATION_BYTES
    + 4
    + MAX_STAGING_INTENT_BYTES
    + 4
    + STORAGE_RPC_MAX_STAGING_ARTIFACT_BYTES;
const STORAGE_RPC_STAGING_ARTIFACT_READ_MAX_RESPONSE_PAYLOAD_LEN: usize = 1
    + 1
    + 4
    + 4
    + METADATA_TRANSFER_STAGED_ARTIFACT_READ_CHUNK_BYTES as usize;
pub(crate) const STORAGE_RPC_STAGING_ARTIFACT_READ_MAX_RESPONSE_FRAME_LEN: usize =
    STORAGE_RPC_FRAME_FIXED_LEN + STORAGE_RPC_STAGING_ARTIFACT_READ_MAX_RESPONSE_PAYLOAD_LEN;
const _: () = assert!(
    STORAGE_RPC_STAGING_AUTHORIZATION_PRESENTATION_OVERHEAD
        + STORAGE_RPC_MAX_STAGING_AUTHORIZATION_BYTES
        + 4
        + MAX_STAGING_INTENT_BYTES
        + 4
        + STORAGE_RPC_MAX_STAGING_ARTIFACT_BYTES
        <= STORAGE_RPC_MAX_PAYLOAD_LEN
);
pub(crate) const STORAGE_RPC_CLIENT_RESPONSE_TIMEOUT: std::time::Duration =
    std::time::Duration::from_secs(1);
pub(crate) const STORAGE_RPC_CLIENT_WRITE_TIMEOUT: std::time::Duration =
    std::time::Duration::from_secs(1);
pub(crate) const STORAGE_RPC_SERVER_IDLE_TIMEOUT: std::time::Duration =
    std::time::Duration::from_secs(1);
const STORAGE_RPC_EMPTY_REQUEST_PAYLOAD_LEN: usize = 0;
pub(crate) const STORAGE_RPC_MAX_READ_OPERATION_ID_LEN: usize = 256;
pub(crate) const STORAGE_RPC_MAX_READ_HANDLE_LOCATIONS: usize = 1024;
pub(crate) const STORAGE_RPC_MAX_SHARD_ACK_ITEMS: usize = 4096;
const STORAGE_RPC_SHARD_LOCATION_LEN: usize = 8 + 4 + 1 + 4;
const STORAGE_RPC_SHARD_KEY_FIELD_LEN: usize = 4 + SHARD_KEY_LEN;
const STORAGE_RPC_WRITE_ACK_LEN: usize = 8 + 8;
const STORAGE_RPC_SHARD_ACK_ROUTE_LEN: usize = 4 + 8 + 4;
const STORAGE_RPC_MAX_SHARD_ACK_ITEM_PAYLOAD_LEN: usize =
    STORAGE_RPC_SHARD_ACK_ROUTE_LEN + STORAGE_RPC_SHARD_KEY_FIELD_LEN;
const STORAGE_RPC_MAX_SHARD_ACK_BATCH_PAYLOAD_LEN: usize = STORAGE_RPC_SHARD_ACK_ROUTE_LEN
    + 4
    + STORAGE_RPC_MAX_SHARD_ACK_ITEMS
        * (STORAGE_RPC_SHARD_KEY_FIELD_LEN + STORAGE_RPC_WRITE_ACK_LEN);
const STORAGE_RPC_MAX_SCAVENGER_SCAN_ERRORS: usize = 4096;
const STORAGE_RPC_MAX_SCAVENGER_SCAN_ERROR_LEN: usize = 4096;
const STORAGE_RPC_MAX_SCAVENGER_LIST_FILES_PAYLOAD_LEN: usize = STORAGE_RPC_SHARD_ACK_ROUTE_LEN;
const STORAGE_RPC_MAX_SHARD_SCAVENGER_REFERENCE_PAGE_REQUEST_PAYLOAD_LEN: usize = 4096;
const STORAGE_RPC_MAX_SHARD_SCAVENGER_REFERENCE_MATCH_REQUEST_PAYLOAD_LEN: usize = 4096;
const STORAGE_RPC_SCAVENGER_FILE_RESPONSE_LEN: usize = STORAGE_RPC_SHARD_KEY_FIELD_LEN + 8;
const STORAGE_RPC_MAX_SCAVENGER_METADATA_ITEMS: usize = 100_000;
const STORAGE_RPC_SCAVENGER_OBSERVATION_KEY_LEN: usize =
    4 + 4 + 1 + STORAGE_RPC_SHARD_KEY_FIELD_LEN;
const STORAGE_RPC_MAX_SCAVENGER_OBSERVATION_ERROR_LEN: usize = 4096;
const STORAGE_RPC_MAX_SCAVENGER_OBSERVATION_RECORD_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + STORAGE_RPC_SCAVENGER_OBSERVATION_KEY_LEN
        + 1
        + 8
        + 1
        + 8
        + 1
        + 1
        + 1
        + 1
        + 4
        + STORAGE_RPC_MAX_SCAVENGER_OBSERVATION_ERROR_LEN;
const STORAGE_RPC_MAX_SCAVENGER_OBSERVATION_KEY_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN + STORAGE_RPC_SCAVENGER_OBSERVATION_KEY_LEN;
const STORAGE_RPC_SCAVENGER_PAYLOAD_REFERENCE_MIN_LEN: usize = 1 + 4 + 16 + 8 + 2;
const STORAGE_RPC_SCAVENGER_OBSERVATION_MIN_LEN: usize =
    STORAGE_RPC_SCAVENGER_OBSERVATION_KEY_LEN + 8 + 8 + 8 + 1 + 1 + 1 + 1 + 1 + 1 + 1;
const STORAGE_RPC_PLACED_SEGMENT_REPAIR_WORK_ITEM_MIN_LEN: usize = 4 + 16 + 8 + 8 + 8 + 2 + 1;
const STORAGE_RPC_PLACED_SEGMENT_REPAIR_WORK_ITEM_MAX_LEN: usize =
    STORAGE_RPC_PLACED_SEGMENT_REPAIR_WORK_ITEM_MIN_LEN;
const STORAGE_RPC_PLACED_SEGMENT_BACKFILL_WORK_ITEM_MIN_LEN: usize = 4 + 16 + 8 + 8 + 8 + 2 + 8 + 8;
const STORAGE_RPC_PLACED_SEGMENT_BACKFILL_WORK_ITEM_MAX_LEN: usize =
    STORAGE_RPC_PLACED_SEGMENT_BACKFILL_WORK_ITEM_MIN_LEN;
const STORAGE_RPC_PLACED_SEGMENT_REPAIR_RECORD_MIN_LEN: usize =
    STORAGE_RPC_PLACED_SEGMENT_REPAIR_WORK_ITEM_MIN_LEN + 8 + 8 + 8 + 1;
const STORAGE_RPC_PLACED_SEGMENT_BACKFILL_RECORD_MIN_LEN: usize =
    STORAGE_RPC_PLACED_SEGMENT_BACKFILL_WORK_ITEM_MIN_LEN + 1 + 8 + 8 + 8 + 1;
const STORAGE_RPC_MAX_PLACED_SEGMENT_REPAIR_RECORD_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + STORAGE_RPC_PLACED_SEGMENT_REPAIR_WORK_ITEM_MAX_LEN
        + 1
        + 4
        + PLACED_SEGMENT_SHARD_REPAIR_LAST_ERROR_MAX_LEN;
const STORAGE_RPC_MAX_PLACED_SEGMENT_BACKFILL_RECORD_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + STORAGE_RPC_PLACED_SEGMENT_BACKFILL_WORK_ITEM_MAX_LEN
        + 1
        + 1
        + 4
        + PLACED_SEGMENT_SHARD_BACKFILL_LAST_ERROR_MAX_LEN;
const STORAGE_RPC_PLACED_SEGMENT_REPAIR_CLAIM_RECORD_MIN_LEN: usize =
    STORAGE_RPC_PLACED_SEGMENT_REPAIR_WORK_ITEM_MIN_LEN + 4 + 4 + 8 + 8 + 1 + 8 + 1;
const STORAGE_RPC_PLACED_SEGMENT_BACKFILL_CLAIM_RECORD_MIN_LEN: usize =
    STORAGE_RPC_PLACED_SEGMENT_BACKFILL_WORK_ITEM_MIN_LEN + 1 + 4 + 4 + 8 + 8 + 1 + 8 + 1;
const STORAGE_RPC_MAX_PLACED_SEGMENT_REPAIR_CLAIM_RECORD_PAYLOAD_LEN: usize =
    STORAGE_RPC_PLACED_SEGMENT_REPAIR_WORK_ITEM_MAX_LEN
        + 4
        + PLACED_SEGMENT_SHARD_REPAIR_CLAIM_ID_MAX_LEN
        + 4
        + PLACED_SEGMENT_SHARD_REPAIR_OWNER_TOKEN_MAX_LEN
        + 8
        + 8
        + 1
        + 8
        + 8
        + 1
        + 4
        + PLACED_SEGMENT_SHARD_REPAIR_LAST_ERROR_MAX_LEN;
const STORAGE_RPC_MAX_PLACED_SEGMENT_BACKFILL_CLAIM_RECORD_PAYLOAD_LEN: usize =
    STORAGE_RPC_PLACED_SEGMENT_BACKFILL_WORK_ITEM_MAX_LEN
        + 1
        + 4
        + PLACED_SEGMENT_SHARD_BACKFILL_CLAIM_ID_MAX_LEN
        + 4
        + PLACED_SEGMENT_SHARD_BACKFILL_OWNER_TOKEN_MAX_LEN
        + 8
        + 8
        + 1
        + 8
        + 8
        + 1
        + 4
        + PLACED_SEGMENT_SHARD_BACKFILL_LAST_ERROR_MAX_LEN;
const STORAGE_RPC_MAX_PLACED_SEGMENT_REPAIR_CLAIM_ACQUIRE_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + 4
        + PLACED_SEGMENT_SHARD_REPAIR_CLAIM_ID_MAX_LEN
        + 4
        + PLACED_SEGMENT_SHARD_REPAIR_OWNER_TOKEN_MAX_LEN
        + 8
        + 1
        + 8
        + 8;
const STORAGE_RPC_MAX_PLACED_SEGMENT_BACKFILL_CLAIM_ACQUIRE_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + 4
        + PLACED_SEGMENT_SHARD_BACKFILL_CLAIM_ID_MAX_LEN
        + 4
        + PLACED_SEGMENT_SHARD_BACKFILL_OWNER_TOKEN_MAX_LEN
        + 8
        + 1
        + 8
        + 8;
const STORAGE_RPC_MAX_PLACED_SEGMENT_REPAIR_CLAIM_ERROR_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + STORAGE_RPC_MAX_PLACED_SEGMENT_REPAIR_CLAIM_RECORD_PAYLOAD_LEN
        + 4
        + PLACED_SEGMENT_SHARD_REPAIR_LAST_ERROR_MAX_LEN
        + 8;
const STORAGE_RPC_MAX_PLACED_SEGMENT_BACKFILL_CLAIM_ERROR_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + STORAGE_RPC_MAX_PLACED_SEGMENT_BACKFILL_CLAIM_RECORD_PAYLOAD_LEN
        + 4
        + PLACED_SEGMENT_SHARD_BACKFILL_LAST_ERROR_MAX_LEN
        + 8;
const STORAGE_RPC_MAX_SHARD_DELETE_PAYLOAD_LEN: usize =
    STORAGE_RPC_SHARD_LOCATION_LEN + STORAGE_RPC_SHARD_KEY_FIELD_LEN;
const STORAGE_RPC_MAX_SHARD_READ_PAYLOAD_LEN: usize =
    STORAGE_RPC_SHARD_LOCATION_LEN + STORAGE_RPC_SHARD_KEY_FIELD_LEN + STORAGE_RPC_WRITE_ACK_LEN;
const STORAGE_RPC_MAX_HISTORICAL_SHARD_READ_PAYLOAD_LEN: usize =
    STORAGE_RPC_SHARD_LOCATION_LEN + STORAGE_RPC_SHARD_KEY_FIELD_LEN;
const STORAGE_RPC_MAX_SHARD_READ_RANGE_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_SHARD_READ_PAYLOAD_LEN + 8 + 8;
const STORAGE_RPC_MAX_READ_HANDLE_ACQUIRE_PAYLOAD_LEN: usize = 4
    + STORAGE_RPC_MAX_READ_OPERATION_ID_LEN
    + 4
    + STORAGE_RPC_MAX_READ_HANDLE_LOCATIONS
        * (STORAGE_RPC_SHARD_LOCATION_LEN + STORAGE_RPC_SHARD_KEY_FIELD_LEN);
const STORAGE_RPC_MAX_READ_HANDLE_RELEASE_PAYLOAD_LEN: usize =
    4 + STORAGE_RPC_MAX_READ_OPERATION_ID_LEN;
const STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN: usize = 4 + 8 + 4;
const STORAGE_RPC_METADATA_PROOF_CARRIER_LEN: usize = 1 + 8;
const STORAGE_RPC_MAX_METADATA_COMMAND_TRANSFER_EMPTY_STATE_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN + STORAGE_RPC_METADATA_PROOF_CARRIER_LEN;
const STORAGE_RPC_MAX_METADATA_COMMAND_TRANSFER_MATCHING_STATE_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + 8
        + STORAGE_RPC_METADATA_PROOF_CARRIER_LEN
        + STORAGE_RPC_METADATA_PROOF_CARRIER_LEN;
const STORAGE_RPC_MAX_METADATA_COMMAND_NEXT_ID_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN + 8;
const STORAGE_RPC_MAX_METADATA_COMMAND_LOG_HASH_RANGE_ENTRIES: u64 = 4096;
const STORAGE_RPC_MAX_METADATA_COMMAND_LOG_HASH_RANGE_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN + 16;
// Keep the worst-case all-applied retained-entry response within the 64 MiB
// frame cap after success-response wrapping.
pub(crate) const STORAGE_RPC_MAX_METADATA_COMMAND_LOG_ENTRY_RANGE_ENTRIES: u64 = 31;
pub(crate) const STORAGE_RPC_MAX_METADATA_COMMAND_CHECKPOINT_CANDIDATES: usize = 4;
pub(crate) const STORAGE_RPC_MAX_METADATA_COMMAND_BYTES_LEN: usize = 2 * 1024 * 1024;
const STORAGE_RPC_MAX_METADATA_CHECKPOINT_TABLES: usize = 128;
const STORAGE_RPC_MAX_METADATA_CHECKPOINT_COLUMNS: usize = 256;
const STORAGE_RPC_MAX_METADATA_CHECKPOINT_ROWS: usize = 100_000;
const STORAGE_RPC_MAX_METADATA_CHECKPOINT_ROW_VALUES: usize = 256;
const STORAGE_RPC_MAX_METADATA_CHECKPOINT_VALUE_BYTES_LEN: usize = 2 * 1024 * 1024;
const STORAGE_RPC_MAX_METADATA_COMMAND_ITEM_PAYLOAD_LEN: usize =
    8 + 4 + STORAGE_RPC_MAX_METADATA_COMMAND_BYTES_LEN;
const STORAGE_RPC_MAX_METADATA_COMMAND_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + STORAGE_RPC_MAX_METADATA_COMMAND_ITEM_PAYLOAD_LEN;
const STORAGE_RPC_MAX_OPERATION_DEADLINE_PAYLOAD_LEN: usize = 1 + 8;
const STORAGE_RPC_MAX_METADATA_COMMAND_PENDING_SLOT_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_REQUEST_PAYLOAD_LEN
        + 1
        + 4
        + STORAGE_RPC_MAX_BUCKET_NAME_LEN
        + 1
        + 16
        + STORAGE_RPC_MAX_OPERATION_DEADLINE_PAYLOAD_LEN;
const STORAGE_RPC_MAX_METADATA_COMMAND_PENDING_SLOT_REPLACE_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + 2 * STORAGE_RPC_MAX_METADATA_COMMAND_ITEM_PAYLOAD_LEN
        + 1
        + 4
        + STORAGE_RPC_MAX_BUCKET_NAME_LEN;
const STORAGE_RPC_MAX_METADATA_COMMAND_RECOVERY_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + 1
        + 3 * STORAGE_RPC_MAX_METADATA_COMMAND_ITEM_PAYLOAD_LEN;
const STORAGE_RPC_MAX_METADATA_COMMAND_RECOVERY_PENDING_SLOT_REPLACE_REQUEST_PAYLOAD_LEN: usize = 1
    + 2 * STORAGE_RPC_MAX_METADATA_COMMAND_ITEM_PAYLOAD_LEN
    + STORAGE_RPC_MAX_METADATA_COMMAND_PENDING_SLOT_REPLACE_REQUEST_PAYLOAD_LEN;
const STORAGE_RPC_MAX_METADATA_COMMAND_MATCHING_APPLIED_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_REQUEST_PAYLOAD_LEN + 8;
const STORAGE_RPC_MAX_BUCKET_NAME_LEN: usize = 63;
const STORAGE_RPC_MAX_BUCKET_NAME_FIELD_LEN: usize = 4 + STORAGE_RPC_MAX_BUCKET_NAME_LEN;
const STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ID_LEN: usize = 256;
const STORAGE_RPC_MAX_BUCKET_WRITE_OWNER_TOKEN_LEN: usize = 1024;
const STORAGE_RPC_MAX_BUCKET_WRITE_OPERATION_KIND_LEN: usize = 128;
const STORAGE_RPC_MAX_BUCKET_WRITE_TARGET_CONTEXT_LEN: usize = 1024;
const STORAGE_RPC_BUCKET_WRITE_RECORD_MAX_LEN: usize = STORAGE_RPC_MAX_BUCKET_NAME_FIELD_LEN
    + 4
    + STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ID_LEN
    + 4
    + STORAGE_RPC_MAX_BUCKET_WRITE_OWNER_TOKEN_LEN
    + 8
    + 8
    + 8
    + 4
    + STORAGE_RPC_MAX_BUCKET_WRITE_OPERATION_KIND_LEN
    + 8
    + 8
    + 1
    + 4
    + STORAGE_RPC_MAX_BUCKET_WRITE_TARGET_CONTEXT_LEN;
const STORAGE_RPC_BUCKET_DELETE_ATTEMPT_OUTCOME_RECORD_MAX_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_NAME_FIELD_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ID_LEN
        + 8
        + 8
        + 1
        + 1
        + 4
        + BUCKET_DELETE_ATTEMPT_OUTCOME_DETAIL_MAX_LEN
        + 1
        + 4
        + 1
        + 4
        + 1
        + 4
        + SESSION_ID_LEN
        + 1
        + 1
        + 4
        + 1
        + 4
        + 8;
const STORAGE_RPC_MAX_BUCKET_OWNER_PRINCIPAL_LEN: usize = 1024;
const STORAGE_RPC_MAX_BUCKET_OWNER_CANONICAL_ID_LEN: usize = 1024;
const STORAGE_RPC_MAX_BUCKET_ACL_GRANTS_LEN: usize = 64 * 1024;
const STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN: usize =
    4 + 8 + 4 + STORAGE_RPC_MAX_BUCKET_NAME_FIELD_LEN;
const STORAGE_RPC_MAX_BUCKET_BATCH_ITEMS: u32 = 100_000;
const STORAGE_RPC_MAX_BUCKET_LIST_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_OWNER_CANONICAL_ID_LEN;
const STORAGE_RPC_MAX_BUCKET_BATCH_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_BATCH_ITEMS as usize * STORAGE_RPC_MAX_BUCKET_NAME_FIELD_LEN;
const STORAGE_RPC_MAX_BUCKET_SNAPSHOT_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN + 4;
const STORAGE_RPC_MAX_OBJECT_KEY_LEN: usize = 1024;
const STORAGE_RPC_MAX_LIST_PAGE_ITEMS: u32 = 100_000;
const STORAGE_RPC_MAX_CLEANUP_LIST_PAGE_ITEMS: u32 = 1024;
const STORAGE_RPC_MAX_STREAM_UPLOADS_LIST_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN + 1 + 4 + SESSION_ID_LEN + 4;
const STORAGE_RPC_MAX_STREAM_UPLOADS_PG_LIST_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN + 1 + 4 + SESSION_ID_LEN + 4;
const STORAGE_RPC_MAX_LIST_OBJECTS_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN + 3 * (1 + 4 + STORAGE_RPC_MAX_OBJECT_KEY_LEN) + 4;
const STORAGE_RPC_MAX_LIST_OBJECT_VERSIONS_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN
        + 3 * (1 + 4 + STORAGE_RPC_MAX_OBJECT_KEY_LEN)
        + 1
        + 8
        + 4;
const STORAGE_RPC_MAX_LIST_MULTIPART_UPLOADS_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN
        + 1
        + 4
        + STORAGE_RPC_MAX_OBJECT_KEY_LEN
        + 1
        + 4
        + STORAGE_RPC_MAX_OBJECT_KEY_LEN
        + 1
        + 4
        + UPLOAD_ID_LEN
        + 4;
const STORAGE_RPC_MAX_OBJECT_GENERATION_REQUEST_PAYLOAD_LEN: usize =
    4 + 8 + 4 + STORAGE_RPC_MAX_BUCKET_NAME_FIELD_LEN + 4 + STORAGE_RPC_MAX_OBJECT_KEY_LEN;
const STORAGE_RPC_MAX_OBJECT_GENERATION_RESERVATION_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_OBJECT_GENERATION_REQUEST_PAYLOAD_LEN + 4 + SESSION_ID_LEN;
const STORAGE_RPC_MAX_OBJECT_VERSION_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_OBJECT_GENERATION_REQUEST_PAYLOAD_LEN;
const STORAGE_RPC_MAX_OBJECT_PAYLOAD_RECLAIM_EXISTS_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_OBJECT_GENERATION_REQUEST_PAYLOAD_LEN + 8;
const STORAGE_RPC_MAX_OBJECT_PAYLOAD_LEASE_CONTROL_REQUEST_PAYLOAD_LEN: usize = 4
    + 8
    + STORAGE_RPC_MAX_BUCKET_NAME_FIELD_LEN
    + 4
    + STORAGE_RPC_MAX_OBJECT_KEY_LEN
    + 8
    + 1
    + 1
    + 8
    + 1
    + 4
    + STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ID_LEN
    + 4
    + STORAGE_RPC_MAX_BUCKET_WRITE_OWNER_TOKEN_LEN
    + 8;
const STORAGE_RPC_OBJECT_PAYLOAD_RECLAIM_CLAIM_RECORD_MAX_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_NAME_FIELD_LEN
        + 8
        + 4
        + STORAGE_RPC_MAX_OBJECT_KEY_LEN
        + 8
        + 1
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ID_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_OWNER_TOKEN_LEN
        + 8
        + 8
        + 1
        + 8
        + 4;
const STORAGE_RPC_MAX_OBJECT_PAYLOAD_RECLAIM_CLAIM_ACQUIRE_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_OBJECT_PAYLOAD_RECLAIM_EXISTS_REQUEST_PAYLOAD_LEN
        + 8
        + 1
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ID_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_OWNER_TOKEN_LEN
        + 8
        + 1
        + 8
        + 8
        + 1
        + 8
        + 8;
const STORAGE_RPC_MAX_OBJECT_PAYLOAD_RECLAIM_CLAIM_RECORD_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + STORAGE_RPC_OBJECT_PAYLOAD_RECLAIM_CLAIM_RECORD_MAX_LEN;
const STORAGE_RPC_MAX_DIRECT_PUT_SNAPSHOT_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_OBJECT_GENERATION_RESERVATION_REQUEST_PAYLOAD_LEN + 8;
const STORAGE_RPC_MAX_DIRECT_PUT_COMMAND_BUILD_REQUEST_PAYLOAD_LEN: usize = 2 * 1024 * 1024;
const STORAGE_RPC_MAX_OBJECT_READ_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_OBJECT_GENERATION_REQUEST_PAYLOAD_LEN + 1 + 8;
const STORAGE_RPC_MAX_OBJECT_READ_SNAPSHOT_REQUEST_PAYLOAD_LEN: usize = 2 * 1024 * 1024;
const STORAGE_RPC_MAX_OBJECT_METADATA_SNAPSHOT_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_OBJECT_READ_REQUEST_PAYLOAD_LEN;
const STORAGE_RPC_MAX_OBJECT_METADATA_COMMAND_BUILD_REQUEST_PAYLOAD_LEN: usize = 2 * 1024 * 1024;
const STORAGE_RPC_MAX_MULTIPART_UPLOAD_LOAD_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_OBJECT_GENERATION_REQUEST_PAYLOAD_LEN + 4 + UPLOAD_ID_LEN;
const STORAGE_RPC_MAX_MULTIPART_COMPLETION_SNAPSHOT_REQUEST_PAYLOAD_LEN: usize = 2 * 1024 * 1024;
const STORAGE_RPC_MAX_MULTIPART_COMPLETION_PREFLIGHT_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_MULTIPART_COMPLETION_SNAPSHOT_REQUEST_PAYLOAD_LEN;
const STORAGE_RPC_MAX_MULTIPART_PARTS_LIST_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_MULTIPART_COMPLETION_SNAPSHOT_REQUEST_PAYLOAD_LEN + 1 + 4 + 4;
const STORAGE_RPC_MAX_MULTIPART_MANAGEMENT_LOOKUP_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_MULTIPART_UPLOAD_LOAD_REQUEST_PAYLOAD_LEN;
const STORAGE_RPC_MAX_MULTIPART_ABORT_CLEANUP_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_OBJECT_GENERATION_REQUEST_PAYLOAD_LEN + 4 + UPLOAD_ID_LEN;
const STORAGE_RPC_MAX_STREAM_PUT_FINALIZE_SNAPSHOT_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_OBJECT_GENERATION_REQUEST_PAYLOAD_LEN + 4 + SESSION_ID_LEN;
const STORAGE_RPC_MAX_STREAM_PART_FINALIZE_SNAPSHOT_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_STREAM_PUT_FINALIZE_SNAPSHOT_REQUEST_PAYLOAD_LEN + 4 + UPLOAD_ID_LEN + 4;
const STORAGE_RPC_MAX_STREAM_UPLOAD_SESSION_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_OBJECT_GENERATION_REQUEST_PAYLOAD_LEN + 4 + SESSION_ID_LEN;
const STORAGE_RPC_MAX_STREAM_UPLOAD_BUCKET_WRITE_RESERVATION_UPDATE_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_STREAM_UPLOAD_SESSION_REQUEST_PAYLOAD_LEN
        + (2 * STORAGE_RPC_BUCKET_WRITE_RECORD_MAX_LEN)
        + 1
        + 16;
const STORAGE_RPC_MAX_STREAM_UPLOAD_SEGMENTS_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_STREAM_UPLOAD_SESSION_REQUEST_PAYLOAD_LEN;
const STORAGE_RPC_MAX_STREAM_SEGMENT_APPEND_PREPARE_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_STREAM_UPLOAD_SESSION_REQUEST_PAYLOAD_LEN + 4 + 8 + 8 + 8 + 1 + 8 + 8;
const STORAGE_RPC_MAX_STREAM_FINALIZE_COMMAND_BUILD_REQUEST_PAYLOAD_LEN: usize = 2 * 1024 * 1024;
const STORAGE_RPC_MAX_MULTIPART_COMPLETION_COMMAND_BUILD_REQUEST_PAYLOAD_LEN: usize =
    2 * 1024 * 1024;
const STORAGE_RPC_MAX_MULTIPART_ABORT_COMMAND_BUILD_REQUEST_PAYLOAD_LEN: usize = 2 * 1024 * 1024;
// A supported reclaim payload can consume nearly the entire metadata-command
// byte budget. The build request carries that payload plus routing, generation,
// full-claim, and portable-deadline fields which are not part of the payload
// itself, so those fields need their own admission budget.
const STORAGE_RPC_OBJECT_PAYLOAD_RECLAIM_COMMAND_BUILD_REQUEST_OVERHEAD_LEN: usize =
    STORAGE_RPC_MAX_OBJECT_GENERATION_REQUEST_PAYLOAD_LEN
        + 8
        + STORAGE_RPC_OBJECT_PAYLOAD_RECLAIM_CLAIM_RECORD_MAX_LEN
        + 1
        + 8
        + 8;
const STORAGE_RPC_MAX_OBJECT_PAYLOAD_RECLAIM_COMMAND_BUILD_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_BYTES_LEN
        + STORAGE_RPC_OBJECT_PAYLOAD_RECLAIM_COMMAND_BUILD_REQUEST_OVERHEAD_LEN;
const STORAGE_RPC_MIN_OBJECT_SEGMENT_RECORD_LEN: usize =
    4 + 4 + 8 + 4 + 8 + 8 + 4 + 16 + 8 + 4 + 8 + 2;
const STORAGE_RPC_MIN_OBJECT_PART_RECORD_LEN: usize =
    4 + 4 + 8 + 4 + 8 + 8 + 4 + 1 + 8 + 8 + 2 + 4 + 1;
const STORAGE_RPC_MIN_STREAM_UPLOAD_SEGMENT_RECORD_LEN: usize =
    4 + SESSION_ID_LEN + 4 + 8 + 8 + 8 + 4 + 16 + 8 + 4 + 8 + 2;
const STORAGE_RPC_MIN_STREAM_UPLOAD_RECORD_LEN: usize =
    4 + SESSION_ID_LEN + 4 + 4 + 1 + 1 + 8 + 1 + 1;
const STORAGE_RPC_MIN_MULTIPART_PART_RECORD_LEN: usize =
    4 + UPLOAD_ID_LEN + 4 + 4 + 8 + 8 + 4 + 1 + 8 + 8 + 2 + 8 + 1;
const STORAGE_RPC_MIN_MULTIPART_PART_SEGMENT_RECORD_LEN: usize =
    4 + 4 + 4 + UPLOAD_ID_LEN + 8 + 4 + 4 + 8 + 8 + 4 + 16 + 8 + 4 + 8 + 2;
const STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ACQUIRE_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ID_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_OWNER_TOKEN_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_OPERATION_KIND_LEN
        + 8
        + 1
        + 8
        + 1
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_TARGET_CONTEXT_LEN
        + 1
        + 16;
const STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_PROOF_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN + STORAGE_RPC_BUCKET_WRITE_RECORD_MAX_LEN;
const STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_HEARTBEAT_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_PROOF_PAYLOAD_LEN + 8 + 1 + 16;
const STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_RECORD_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN + STORAGE_RPC_BUCKET_WRITE_RECORD_MAX_LEN;
const STORAGE_RPC_BUCKET_WRITE_DRAIN_RECORD_MAX_LEN: usize = STORAGE_RPC_MAX_BUCKET_NAME_FIELD_LEN
    + 4
    + STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ID_LEN
    + 4
    + STORAGE_RPC_MAX_BUCKET_WRITE_OWNER_TOKEN_LEN
    + 8
    + 8
    + 1
    + 8
    + 8;
const STORAGE_RPC_MAX_BUCKET_WRITE_DRAIN_BEGIN_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ID_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_OWNER_TOKEN_LEN
        + 8
        + 8
        + 1
        + 8
        + 8;
const STORAGE_RPC_MAX_BUCKET_WRITE_DRAIN_RECORD_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + STORAGE_RPC_BUCKET_WRITE_DRAIN_RECORD_MAX_LEN;
const STORAGE_RPC_MAX_BUCKET_WRITE_DRAIN_HEARTBEAT_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_WRITE_DRAIN_RECORD_PAYLOAD_LEN + 8;
const STORAGE_RPC_MAX_BUCKET_WRITE_DRAIN_EXPIRED_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN + 8;
const STORAGE_RPC_MAX_BUCKET_DELETE_ATTEMPT_OUTCOME_RECORD_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + STORAGE_RPC_BUCKET_DELETE_ATTEMPT_OUTCOME_RECORD_MAX_LEN;
const STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATIONS_LIST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN;
const STORAGE_RPC_MAX_BUCKET_DELETE_FINALIZE_ROOTS_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN + 8 + 4;
const STORAGE_RPC_MAX_BUCKET_DELETE_BEGIN_ROOTS_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + 8
        + 1
        + 4
        + STORAGE_RPC_MAX_BUCKET_NAME_LEN
        + 4;
const STORAGE_RPC_MAX_BUCKET_DELETE_FINALIZE_ROOTS: usize = 1024;
const STORAGE_RPC_MAX_BUCKET_DELETE_BEGIN_ROOTS: usize = 1024;
const STORAGE_RPC_MAX_LIFECYCLE_SWEEP_ROOTS: usize = 1024;
const STORAGE_RPC_BUCKET_DELETE_FINALIZE_ROOT_MAX_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_NAME_FIELD_LEN + 8;
const STORAGE_RPC_BUCKET_DELETE_BEGIN_ROOT_MAX_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_NAME_FIELD_LEN + 8 + 8;
const STORAGE_RPC_BUCKET_DELETE_FINALIZE_CLAIM_RECORD_MAX_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_NAME_FIELD_LEN
        + 8
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ID_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_OWNER_TOKEN_LEN
        + 8
        + 4
        + 8
        + 9
        + 8
        + 5
        + STORAGE_RPC_MAX_BUCKET_WRITE_TARGET_CONTEXT_LEN;
const STORAGE_RPC_MAX_BUCKET_DELETE_FINALIZE_CLAIM_ACQUIRE_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN
        + 8
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ID_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_OWNER_TOKEN_LEN
        + 8
        + 9
        + 8;
const STORAGE_RPC_MAX_BUCKET_DELETE_FINALIZE_CLAIM_RECORD_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_METADATA_COMMAND_STATE_PAYLOAD_LEN
        + STORAGE_RPC_BUCKET_DELETE_FINALIZE_CLAIM_RECORD_MAX_LEN;
const STORAGE_RPC_MAX_CREATE_BUCKET_COMMAND_BUILD_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN
        + 8
        + 4
        + STORAGE_RPC_MAX_BUCKET_NAME_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_OWNER_PRINCIPAL_LEN
        + 4
        + s3_types::CANONICAL_USER_ID_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_ACL_GRANTS_LEN
        + 12;
const STORAGE_RPC_MAX_MULTIPART_COMPLETION_BARRIER_COMMAND_BUILD_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN
        + 8
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_TARGET_CONTEXT_LEN
        + STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_PROOF_PAYLOAD_LEN;
const STORAGE_RPC_MAX_BUCKET_METADATA_CONTROL_REQUEST_PAYLOAD_LEN: usize = 2 * 1024 * 1024;
const STORAGE_RPC_MAX_BUCKET_SUBRESOURCE_GET_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN + 1;
const STORAGE_RPC_MAX_LIFECYCLE_SWEEP_ROOTS_REQUEST_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_WRITE_DRAIN_RECORD_PAYLOAD_LEN;
const STORAGE_RPC_MAX_LIFECYCLE_SWEEP_CLAIM_ACQUIRE_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_REQUEST_PAYLOAD_LEN
        + 8
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ID_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_OWNER_TOKEN_LEN
        + 8
        + 1
        + 8
        + 8;
const STORAGE_RPC_MAX_LIFECYCLE_SWEEP_CLAIM_RECORD_PAYLOAD_LEN: usize =
    STORAGE_RPC_BUCKET_WRITE_RECORD_MAX_LEN + 8 + 4 + 4096;
const STORAGE_RPC_MAX_LIFECYCLE_SWEEP_CLAIM_ERROR_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_LIFECYCLE_SWEEP_CLAIM_RECORD_PAYLOAD_LEN + 4 + 4096;
const STORAGE_RPC_MAX_BUCKET_CLAIM_TOKEN_PAYLOAD_LEN: usize = STORAGE_RPC_MAX_BUCKET_NAME_FIELD_LEN
    + 8
    + 4
    + STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ID_LEN
    + 4
    + STORAGE_RPC_MAX_BUCKET_WRITE_OWNER_TOKEN_LEN
    + 8
    + 4;
const STORAGE_RPC_MAX_OBJECT_PAYLOAD_RECLAIM_CLAIM_TOKEN_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_BUCKET_NAME_FIELD_LEN
        + 8
        + 4
        + STORAGE_RPC_MAX_OBJECT_KEY_LEN
        + 8
        + 1
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_RESERVATION_ID_LEN
        + 4
        + STORAGE_RPC_MAX_BUCKET_WRITE_OWNER_TOKEN_LEN
        + 8
        + 4;
const STORAGE_RPC_MAX_DURABLE_CLAIM_TOKEN_PAYLOAD_LEN: usize = 1
    + if STORAGE_RPC_MAX_OBJECT_PAYLOAD_RECLAIM_CLAIM_TOKEN_PAYLOAD_LEN
        > STORAGE_RPC_MAX_BUCKET_CLAIM_TOKEN_PAYLOAD_LEN
    {
        STORAGE_RPC_MAX_OBJECT_PAYLOAD_RECLAIM_CLAIM_TOKEN_PAYLOAD_LEN
    } else {
        STORAGE_RPC_MAX_BUCKET_CLAIM_TOKEN_PAYLOAD_LEN
    };
const STORAGE_RPC_MAX_CLAIM_HEARTBEAT_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_DURABLE_CLAIM_TOKEN_PAYLOAD_LEN + 8 + 1 + 8;
const STORAGE_RPC_MAX_CLAIM_RELEASE_PAYLOAD_LEN: usize =
    STORAGE_RPC_MAX_DURABLE_CLAIM_TOKEN_PAYLOAD_LEN;
