[package]
name = "server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "argmin-s3"
path = "src/main.rs"

[dependencies]
auth = { path = "../auth" }
crc64 = { path = "../crc64" }
ec = { path = "../ec" }
storage = { path = "../storage" }
base64 = "0.22"
ec-sys = { path = "../ec-sys" }
rapidhash = "1"
ring = "0.17"
thiserror = "2"
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = "0.1"
http = "1"
bytes = "1"
tokio = { version = "1", features = ["rt-multi-thread", "net", "macros", "sync", "time"] }

[dev-dependencies]
tempfile = "3"
