[package]
name = "argmin-crypto"
version = "0.1.0"
edition = "2021"

[lints.clippy]
missing_safety_doc = "deny"
undocumented_unsafe_blocks = "deny"

[features]
default = ["ring"]
ring = ["dep:md5_legacy", "dep:ring"]
openssl = ["dep:openssl", "dep:openssl-sys"]

[dependencies]
md5_legacy = { package = "md-5", version = "0.10", optional = true }
openssl = { version = "0.10", optional = true }
openssl-sys = { version = "0.9", optional = true }
ring = { version = "0.17", optional = true }

[dev-dependencies]
md5_legacy = { package = "md-5", version = "0.10" }
proptest = "1"
ring = "0.17"
